# conda env export --from-history | grep -v "prefix" > environment.yml
name: pixel_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - pandas
  - scipy
  - scikit-learn
  - pytorch=1.10
  - seaborn
  - lightgbm
  - jupyter
  - opencv
  - optuna
  - ca-certificates
  - certifi
  - openssl
  - scikit-optimize
  - scikit-image
  - torchvision
  - jupyter_contrib_nbextensions
