name: pixel_env
channels:
  - pytorch
  - defaults
dependencies:
  - anaconda
  - python=3.10
  - pytorch
  - torchvision
  - scipy
  - seaborn
  - lightgbm
  - pandas
  - scikit-learn
  - matplotlib
  - scikit-optimize
  - scikit-image
  - ca-certificates
  - certifi
  - openssl
  - openblas
  pip:
  - opencv-python
  - tqdm
